# Generated by Django 3.2.20 on 2023-09-19 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0054_donor_in_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image_url', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_links', to='blood_donate.footer')),
            ],
        ),
        migrations.CreateModel(
            name='MobileAppLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_icon', models.ImageField(upload_to='media')),
                ('url', models.URLField()),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_app_links', to='blood_donate.footer')),
            ],
        ),
        migrations.CreateModel(
            name='LookingForBloodLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looking_for_blood_links', to='blood_donate.footer')),
            ],
        ),
        migrations.AddField(
            model_name='footer',
            name='social_links',
            field=models.ManyToManyField(to='blood_donate.SocialLink'),
        ),
    ]
